name: Auto Sync Fork

on:
  schedule:
    - cron: '10 10 * * *'
      timezone: 'Asia/Shanghai'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - name: Sync fork with upstream
        run: gh repo sync "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Keep workflow alive
        if: github.event_name == 'schedule'
        shell: bash
        run: |
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"

          echo "Keeping workflow alive: ${workflow}"

          gh api \
            --method PUT \
            "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
        env:
          GH_TOKEN: ${{ github.token }}
